/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/
var Traffix;
(function (Traffix) {
    var Models;
    (function (Models) {
        Models.Role = {
            Low: "Low",
            Medium: "Medium",
            High: "High",
        };
        Models.EnumLabelDictionary = {
            "RoleLow": "Minimal Congestion",
            "RoleMedium": "Medium Congestion",
            "RoleHigh": "High Congestion",
            get: function (type, key) {
                return this[type + key];
            }
        };
    })(Models = Traffix.Models || (Traffix.Models = {}));
})(Traffix || (Traffix = {}));
//# sourceMappingURL=Enums.js.map