
/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/

module Traffix.Models {

	 export type IRole = "Low" | "Medium" | "High";


	 export const Role = {
		 Low: "Low" as IRole,
		 Medium: "Medium" as IRole,
		 High: "High" as IRole,
	 }
	export const EnumLabelDictionary = {
		"RoleLow":"Minimal Congestion",
		"RoleMedium":"Medium Congestion",
		"RoleHigh":"High Congestion",
		get: function(type, key) {
			return this[type + key];
		}
	}
}


