
/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/

module Traffix.Models {

	 export type ICongestionTypes = "Low" | "Medium" | "High";


	 export const CongestionTypes = {
		 Low: "Low" as ICongestionTypes,
		 Medium: "Medium" as ICongestionTypes,
		 High: "High" as ICongestionTypes,
	 }
	export const EnumLabelDictionary = {
		"CongestionTypesLow":"Minimal Congestion",
		"CongestionTypesMedium":"Medium Congestion",
		"CongestionTypesHigh":"High Congestion",
		get: function(type, key) {
			return this[type + key];
		}
	}
}


